### ISSUE TITLE
Couldn't create dex file

### ISSUE THREAD

**Issue by aostv10** [artyomd/Injector#99] opened 2019-10-22 21:13 UTC
Good bug reports include a failing test! Creating a minimal project for reproducing the issue will help us to fix it fast.
I couldn't run debug or release task.how to run this task? every time shows
 Task 'createInjectReleaseDexes' not found in project 
How to solved this problem??

**Comment by artyomd** [comment] 2019-10-23 16:38
Thanks for opening issue. I am planning to cover all project with test but unfortunately I do not have enough time. So could you pls provide an example project for your issue?

**Comment by ar13101085** [comment] 2019-10-24 12:34
here is my example project,
https://github.com/ar13101085/vlc-demo

**Comment by ar13101085** [comment] 2019-10-24 12:37
<img width="1552" alt="Screenshot 2019-10-24 at 6 35 38 PM" src="https://user-images.githubusercontent.com/22417217/67486090-28fcf980-f68d-11e9-8c15-b231f2f15cc9.png">
here i attached my photo.can you please check

**Comment by artyomd** [comment] 2019-10-24 17:20
@ar13101085 thanks for reporting this "bug". After analyzing your setup I understood that this is intended behavior. I have implemented the plugin in the way if there are not any inject dependencies it will not create createInject<Variant>Task. So thanks for opening this issue, I will update the documentation or change the implementation. Thank you

**Comment by ar13101085** [comment] 2019-10-24 17:23
Then how i can create dex file?

**Comment by ar13101085** [comment] 2019-10-24 17:27
Can you please update the documentation and also update my project?

**Comment by artyomd** [comment] 2019-10-24 17:51
@ar13101085 regarding your project pls explain what you wanted to achieve

**Comment by ar13101085** [comment] 2019-10-24 18:05
I want to create dynamicLib module dex file.then i want to load this dex file on my demo-vlc project.when i release my apk, if i need update apk, i just want to update dynamicLib module and make a dex file. then apk load this dex file from server. i Don't want to update user full apk. they just download and install apk only one time.if need update just download dex and load this dex at runtime

**Comment by artyomd** [comment] 2019-10-24 18:12
In that case, you should create your app module then a library module then your DynamicLib module and the dependency structure is the following app->library module-> DynamicLib. In your Library module, you apply the injector plugin and declare DynamicLib as inject depending and everything will work. So if you are wondering why you should create the second library module it is because android gradle plugin does not support compileOnly configuration in the application extension

**Comment by ar13101085** [comment] 2019-10-24 18:20
Thank you so much, then i will try. but can you tell me is automatically generate dex file or need another step to make library module dex file?

**Comment by artyomd** [comment] 2019-10-24 18:30
If you create the project as I described above you can create DynamicLib module to dex file just by using the task provided by injector

**Comment by ar13101085** [comment] 2019-10-25 04:58
Thank you so much, now i can create dex file if i using inject 'com.airbnb.android:lottie:3.1.0' or other dependency.but now my problem is how to use 
implementation project(path: ':dynamiclib')
as `inject project(path: ':dynamiclib')` or `inject 'dynamiclib.aar'` ??

**Comment by artyomd** [comment] 2019-11-01 02:27
`inject project(path: ':dynamiclib')`

**Comment by artyomd** [comment] 2019-11-01 02:27
I am closing this issue if you don't have any more questions

**Closed** 2019-11-02 01:57 UTC
Labels: bug

**Comment by 1priyank1** [comment] 2020-03-19 12:07
When we create a project as described in [this comment](https://github.com/artyomd/Injector/issues/99#issuecomment-546038286), it gives error as below while building.

> A problem occurred configuring project ':mylibrary'.
> > Could not resolve all dependencies for configuration ':mylibrary:inject'.
>    > Could not resolve project :dynamiclib.
>      Required by:
>          project :mylibrary
>       > Cannot choose between the following variants of project :dynamiclib:
>           - debugRuntimeElements
>           - releaseRuntimeElements
>         All of them match the consumer attributes:
>           - Variant 'debugRuntimeElements' capability vlc-demo:dynamiclib:unspecified:
>               - Unmatched attributes:
>                   - Found com.android.build.api.attributes.BuildTypeAttr 'debug' but wasn't required.
>                   - Found com.android.build.api.attributes.VariantAttr 'debug' but wasn't required.
>                   - Found com.android.build.gradle.internal.dependency.AndroidTypeAttr 'Aar' but wasn't required.
>                   - Found org.gradle.usage 'java-runtime' but wasn't required.
>           - Variant 'releaseRuntimeElements' capability vlc-demo:dynamiclib:unspecified:
>               - Unmatched attributes:
>                   - Found com.android.build.api.attributes.BuildTypeAttr 'release' but wasn't required.
>                   - Found com.android.build.api.attributes.VariantAttr 'release' but wasn't required.
>                   - Found com.android.build.gradle.internal.dependency.AndroidTypeAttr 'Aar' but wasn't required.
>                   - Found org.gradle.usage 'java-runtime' but wasn't required.
> 
>
